### ISSUE TITLE
Crash on Android : `WaveformExtractor$startDecode$1$1.onInputBufferAvailable`

### ISSUE THREAD

**Issue by Tom3652** [SimformSolutionsPvtLtd/audio_waveforms#286]
Thanks for the package ! 

**Describe the bug**

I have got this crash from my live app on Android : `WaveformExtractor$startDecode$1$1.onInputBufferAvailable
android.media.MediaCodec$CodecException - Error <address>`

Here is the relevant part of the stack trace from my Firebase Crashlytics dashboard. 

```

Fatal Exception: android.media.MediaCodec$CodecException: Error 0x80000000
       at android.media.MediaCodec.native_queueInputBuffer(MediaCodec.java)
       at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2559)
       at com.simform.audio_waveforms.WaveformExtractor$startDecode$1$1.onInputBufferAvailable(WaveformExtractor.kt:47)
       at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1767)
       at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1705)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**To Reproduce**
No idea how to reproduce since it happened on my live app on the Play Store.

**Expected behavior**
The android app has crashed

**Smartphone (please complete the following information):**
- Device: Samsung galaxy A70
- OS: Android 
- Version : 11

**Comment by Ujas-Majithiya** [comment]
The error code **0x80000000** is not very informative but there are three possibilities due to which this could be happening:
1. Out-of-memory issue (Maybe try limiting the amount of waveform extraction that takes place at the same time)
2. The codec isn't supported by the device (Highly unlikely but worth mentioning)
3. The media file is under DRM protection (Could be this also)

**Comment by Tom3652** [comment]
Thanks for the quick answer ! 

I would go for the OOM issue then, i will try to reduce as you mentioned.
Very nice job by the way for the package.

**Comment by ujas-m-simformsolutions** [comment]
Thank you. Closing this issue for now. Feel free to create a new one if you face any issues.
