### ISSUE TITLE
[iOS] - Unhandled Exception: PlatformException

### ISSUE THREAD

**Issue by Hvt261** [SimformSolutionsPvtLtd/audio_waveforms#335]
I face the issue on iOS when start recording:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(AudioWaveforms, Failed to start recording, The operation couldn’t be completed. (OSStatus error 1718449215.), null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      AudioWaveformsInterface.record (package:audio_waveforms/src/base/audio_waveforms_interface.dart:19:25)
<asynchronous suspension>
#3      RecorderController.record (package:audio_waveforms/src/controllers/recorder_controller.dart:196:26)
<asynchronous suspension>

**Comment by Hvt261** [comment]
I closed this issue because of ios recording only work with ouput is ".m4a" and iosEncoder is "kAudioFormatMPEG4AAC"
