### ISSUE TITLE
Example of a file path for player

### ISSUE THREAD

**Issue by babyken** [SimformSolutionsPvtLtd/audio_waveforms#56]
```
I/flutter (13493): My File path: /data/user/0/com.example.testdrive/app_flutter/mysound-2022-06-09_22:07:02.483249.mp4
I/flutter (13493): My File path: /data/user/0/com.example.testdrive/app_flutter/mysound-2022-06-08_22:52:26.804572.mp4
I/ExoPlayerImpl(13493): Init 81a792b [ExoPlayerLib/2.17.1] [generic_x86_arm, AOSP on IA Emulator, Google, 28]
I/ExoPlayerImpl(13493): Init 500945d [ExoPlayerLib/2.17.1] [generic_x86_arm, AOSP on IA Emulator, Google, 28]
E/ExoPlayerImplInternal(13493): Playback error
E/ExoPlayerImplInternal(13493):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(13493):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
E/ExoPlayerImplInternal(13493):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
E/ExoPlayerImplInternal(13493):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(13493):       at android.os.Looper.loop(Looper.java:193)
E/ExoPlayerImplInternal(13493):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(13493):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.MalformedURLException: no protocol: /data/user/0/com.example.testdrive/app_flutter/mysound-2022-06-09_22:07:02.483249.mp4
E/ExoPlayerImplInternal(13493):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:365)
E/ExoPlayerImplInternal(13493):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
E/ExoPlayerImplInternal(13493):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(13493):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
E/ExoPlayerImplInternal(13493):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(13493):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(13493):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(13493):       at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal(13493):   Caused by: java.net.MalformedURLException: no protocol: /data/user/0/com.example.testdrive/app_flutter/mysound-2022-06-09_22:07:02.483249.mp4
E/ExoPlayerImplInternal(13493):       at java.net.URL.<init>(URL.java:601)
E/ExoPlayerImplInternal(13493):       at java.net.URL.<init>(URL.java:498)
E/ExoPlayerImplInternal(13493):       at java.net.URL.<init>(URL.java:447)
E/ExoPlayerImplInternal(13493):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:507)
E/ExoPlayerImplInternal(13493):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:359)
E/ExoPlayerImplInternal(13493):       ... 7 more
```

I would like to play a file which is saved in app directory
`/data/user/0/com.example.testdrive/app_flutter/mysound-2022-06-09_22:07:02.483249.mp4`

But it said 
`Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.MalformedURLException: no protocol: /data/user/0/com.example.testdrive/app_flutter/mysound-2022-06-09_22:07:02.483249.mp4`

I have tried adding `file:/` or `file://`. However it gives another error which is
`Please provide a valid file path`

Is there any example of what should a file path looks like ??

Thank you

**Comment by nawafAlkhadidi** [comment]
same hare

**Comment by william-herring** [comment]
Hi @babyken, please refer to issue https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues/35 to help with your problem.

**Comment by Ujas-Majithiya** [comment]
@babyken @nawafAlkhadidi Have you tried solution in #35 and try removing `file://` and just provide the path like `/dir1/dir2`
if this still doesn't work then please update it here.

**Comment by babyken** [comment]
@william-herring  and @Ujas-Majithiya 
Thank you for the replies. I tried both with `file://` and without `file://`
which gives different error as mention above.

Eventually I used ffmpeg to solve my problem.

**Comment by Ujas-Majithiya** [comment]
@babyken Thank you for your quick reply, I will look into this and will update here

**Comment by Ujas-Majithiya** [comment]
@babyken  I just noticed you are providing a video file, this plugin is to show waveforms from audio files only

**Comment by ujas-m-simformsolutions** [comment]
With the new `0.1.4` release it should be easier to add the path to the file as we are now using `URI` to get the path.
