### ISSUE TITLE
Can't load file path

### ISSUE THREAD

**Issue by brainer3220** [SimformSolutionsPvtLtd/audio_waveforms#88]
```shell
E/flutter ( 8529): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Please provide a valid file path
E/flutter ( 8529): #0      PlayerController._readAudioFile (package:audio_waveforms/src/controllers/player_controller.dart:74:7)
E/flutter ( 8529): <asynchronous suspension>
E/flutter ( 8529): #1      PlayerController.preparePlayer (package:audio_waveforms/src/controllers/player_controller.dart:90:5)
E/flutter ( 8529): <asynchronous suspension>
E/flutter ( 8529): 
```

I tried below code for load Music, but I got error.

but other library(audioplayers) can work.

```dart
static const audioSet = "assets/audio/HoldOn.mp3";
playerController.preparePlayer(audioSet);
```

version: 0.1.4

**Comment by ujas-m-simformsolutions** [comment]
Hey @brainer3220 if you check the example app, we have used audio assets available in the project itself. So you need to create a file inside your app like this
```dart
final file1 = File('${appDirectory.path}/audio1.mp3');
await file1.writeAsBytes(
        (await  await rootBundle.load(path)).buffer.asUint8List());
playerController1.preparePlayer(file1.path);
```

**Comment by brainer3220** [comment]
@ujas-m-simformsolutions Thanks, I successfully load audio file.

But, I can't view Waveform view in Android or others.
